
  capabilities:
    image: ghcr.io/neosofia/capabilities
    build:
      context: ../capabilities
    container_name: cdp-capabilities
    env_file:
      - ../capabilities/.env.example
    environment:
      ENV: development
    ports:
      - "8019:8019"
